### PR TITLE
Update for Stardew Valley 1.2, streamline build process, and simplify code

### PR DESCRIPTION
**Pull request by Pathoschild**
GateOpener doesn't work in the latest version of SMAPI. Players see this error:
```
A mod failed handling the GameEvents.FourthUpdateTick event:
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<Microsoft.Xna.Framework.Vector2> StardewValley.Character.getAdjacentTiles()'.
at GateOpener.GateOpenerMainClass.Event_Update(Object sender, EventArgs e)
at StardewModdingAPI.Framework.InternalExtensions.SafelyRaisePlainEvent(IMonitor monitor, String name, IEnumerable`1 handlers, Object sender, EventArgs args) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\InternalExtensions.cs:line 46
```

This pull request mainly...
- Updates the code for Stardew Valley 1.2.
- Formats and simplifies the code a bit (e.g. using SMAPI features or C# 7 where possible).
- Migrates the project to the [mod build package](https://github.com/Pathoschild/Stardew.ModBuildConfig).  
  _This automates references (so we no longer need to change reference paths in the `.csproj`), lets us compile the mod on Linux/Mac/Windows without changes, and simplifies debugging from Visual Studio._
- Switches to a build task to automatically package the mod into the `Mods` folder that works on Linux/Mac/Windows.
- Updates and expands the readme.

If the changes all look good, can you release [GateOpener-1.1.zip](https://github.com/mralbobo/stardew-gate-opener/files/953911/GateOpener-1.1.zip) for players to use?

### CODE REVIEW

**Comment by mralbobo** [comment]
You missing a local commit by any chance?
Does not compile...

**Comment by Pathoschild** [comment]
@mralbobo What error are you getting?

**Comment by mralbobo** [comment]
Quite a few actually, mostly syntax errors.

The first one:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1003	Syntax error, ',' expected	GateOpener	C:\Users\mralbobo\repos\GateOpener\ChestPooling\GateOpenerMain.cs	50	Active

if (!location.objects.TryGetValue(pos, out StardewValley.Object obj))


Don't think this is valid syntax (I could be wrong, but it is complaining...):
if (Game1.currentLocation is BuildableGameLocation location)

**Comment by Pathoschild** [comment]
It sounds like you don't have [Visual Studio 2017](https://www.visualstudio.com/vs/community/) (or an equivalent IDE on Linux/Mac), so you can't compile C# 7. Do you want me to add a commit to remove any C# 7 features?

**Comment by mralbobo** [comment]
I'll update from 2015 first and see how that goes...

**Comment by mralbobo** [comment]
That did it. Also did terrible terrible git things (rewriting history).

**Pull request merged**
